version: 2

config:
  send_anonymous_usage_stats: false

sqlpatterns:
  target: dev
  outputs:
    dev:
      path: sqlpatterns.ddb
      schema: main
      type: duckdb
      threads: 4
      extensions:
        - httpfs
        - parquet
